spring.application.name=dfs-data-node
server.port=8001

# Path where this specific node will dump its file blocks
storage.directory=D:/Data-DisK/data

# Spring Web configuration to handle large file block transfers
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB